---
train_model: 0
test_model: 1
model_cfg:
  text_embedding: 
      model_name: "distilbert-base-uncased-finetuned-sst-2-english"
      features_type: "[CLS]" #choices are "[CLS]", "AVG" or "ALL"
train_cfg:
  data_path: "/home/achkan/Desktop/tmp_desktop/train_data_1/described_archive_4418.pkl"
  hyperparams:
    batch_size: 4
    lr: -1
test_cfg:
  data_path: "/home/achkan/Desktop/tmp_desktop/train_data_1/described_archive_4418.pkl"
  batch_size: 4
  debug: 
      test_text_embedding_random_batch: 1
logging: 
  save_weights_to: "/tmp/"

  







